# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37a981e89c34c6b1ff102823d7bfa5ec5ec1672871fabb0bd2737f767ed6fdd8670e21cfb72178e94848ea149f6b2ec49aca9df4a56533fb666f9b283936e67d

test:
  secret_key_base: 515dcbab1475248398e9304f0fba5c93cf7effa3fca7aedb643968b6d5bd71886a1c4efe1dccfbd378973bafd6277e3a60bb3f20a270d33fd953ae571247e9b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
